title: <p align="center"> Harshit Bohra </p>
logo: /assets/img/photo.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/harshit-bohra-b46866154/">LinkedIn</a> |
  <a href="https://github.com/hbohra1992">GitHub</a>  
  <br>   
  I'm working on Data Science, Machine learning & Deep Learning related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
